=== PSICQUIC/psicquic-webservice/psicquic-registry/src/main/resources/META-INF/schema/psicquic-registry.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - 30 Day Trial Edition 7.1.6.1440 (http://www.liquid-technologies.com)-->
<xs:schema xmlns="http://hupo.psi.org/psicquic/registry" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://hupo.psi.org/psicquic/registry" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="registry" type="registryType" />
  <xs:complexType name="registryType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="service" type="serviceType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="serviceType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element name="soapUrl" type="xs:string" />
      <xs:element name="restUrl" type="xs:string" />
      <xs:element type="xs:string" name="restExample"/>
      <xs:element name="active" type="xs:boolean" />
      <xs:element name="count" type="xs:long" />
      <xs:element name="version" type="xs:string" />
      <xs:element name="organizationUrl" type="xs:string" />
      <xs:element name="comments" type="xs:string" />
      <xs:element name="restricted" type="xs:boolean" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="tag" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== PSICQUIC/psicquic-webservice/psicquic-registry/src/main/resources/META-INF/registry.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio - 30 Day Trial Edition 7.1.6.1440 (http://www.liquid-technologies.com) -->
<tns:registry xmlns:tns="http://hupo.psi.org/psicquic/registry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hupo.psi.org/psicquic/registry file:///C:/Users/Erik%20Pfeiffenberger/workspace/psicquic-registry/src/main/resources/META-INF/schema/psicquic-registry.xsd">
  <tns:service>
    <tns:name>BioGrid</tns:name>
    <tns:soapUrl>http://tyerslab.bio.ed.ac.uk:8080/psicquic-ws/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://tyerslab.bio.ed.ac.uk:8080/psicquic-ws/webservices/current/search/interactor/brca2</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://www.thebiogrid.org/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>ChEMBL</tns:name>
    <tns:soapUrl>http://www.ebi.ac.uk/Tools/webservices/psicquic/chembl/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://www.ebi.ac.uk/Tools/webservices/psicquic/chembl/webservices/current/search/interactor/imatinib</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://www.ebi.ac.uk/chembl/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>

  <tns:service>
    <tns:name>IntAct</tns:name>
    <tns:soapUrl>http://www.ebi.ac.uk/Tools/webservices/psicquic/intact/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://www.ebi.ac.uk/Tools/webservices/psicquic/intact/webservices/current/search/query/species:human?firstResult=0&amp;maxResults=100</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://www.ebi.ac.uk/intact</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
	<tns:tag>MI:0960</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>iRefIndex</tns:name>
    <tns:soapUrl>http://biotin.uio.no:8080/psicquic-ws/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://biotin.uio.no:8080/psicquic-ws/webservices/current/search/query/A8K4B6</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://irefindex.uio.no/wiki/iRefIndex/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>MatrixDB</tns:name>
    <tns:soapUrl>http://matrixdb.ibcp.fr:8080/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://matrixdb.ibcp.fr:8080/webservices/current/search/query/*</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://matrixdb.ibcp.fr/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>MINT</tns:name>
    <tns:soapUrl>http://mint.bio.uniroma2.it/mint/psicquic/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://mint.bio.uniroma2.it/mint/psicquic/webservices/current/search/query/p53</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://mint.bio.uniroma2.it/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>MPIDB</tns:name>
    <tns:soapUrl>http://www.jcvi.org/mpidb/servlet/webservices/psicquic</tns:soapUrl>
    <tns:restUrl></tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://www.jcvi.org/mpidb/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>STRING</tns:name>
    <tns:soapUrl>http://string-db.org/psicquic/ws</tns:soapUrl>
    <tns:restUrl></tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://string-db.org/</tns:organizationUrl>
    <tns:comments>'getByInteraction' is not implemented  - we don't have interaction IDs &lt;br/>'getByQuery' - coming soon.&lt;br/>Contact STRING for licensing info.</tns:comments>
    <tns:restricted>true</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>Reactome</tns:name>
    <tns:soapUrl>http://brie8.cshl.edu:8090/psicquic-ws-reactome/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://brie8.cshl.edu:8090/psicquic-ws-reactome/webservices/current/search/query/Q5VT97</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://www.reactome.org/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
	
  <tns:service>
    <tns:name>Reactome Functional Interactions</tns:name>
    <tns:soapUrl>http://brie8.cshl.edu:8090/psicquic-ws-reactome-fi/webservices/psicquic</tns:soapUrl>
    <tns:restUrl>http://brie8.cshl.edu:8090/psicquic-ws-reactome-fi/webservices/current/search/interactor/P00533</tns:restUrl>
    <tns:active>false</tns:active>
    <tns:count>0</tns:count>
    <tns:version></tns:version>
    <tns:organizationUrl>http://www.reactome.org/</tns:organizationUrl>
    <tns:comments></tns:comments>
    <tns:restricted>false</tns:restricted>
    <tns:tag>MI:0959</tns:tag>
  </tns:service>
 
</tns:registry>
